# Generated by Django 4.2 on 2024-08-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_rename_content_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='name',
        ),
    ]
